from __future__ import annotations

from datetime import datetime
from pathlib import Path
from typing import Iterable

from scanner import Finding


HTML_TEMPLATE = """<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Zinkx Dev Assistant — Project Scan</title>
<meta name="viewport" content="width=device-width, initial-scale=1">
<style>
:root {{
  --bg: #0d1117;
  --panel: #161b22;
  --text: #e6edf3;
  --muted: #8b949e;
  --risk: #ff6b6b;
  --todo: #f7b731;
  --info: #4dabf7;
  --border: #30363d;
}}

* {{ box-sizing: border-box; }}

body {{
  margin: 0;
  padding: 24px;
  background: var(--bg);
  color: var(--text);
  font-family: -apple-system, BlinkMacSystemFont, "Inter", "SF Pro Text", sans-serif;
}}

h1 {{ margin-top: 0; }}
h2 {{ margin-top: 32px; }}

.card {{
  background: var(--panel);
  border: 1px solid var(--border);
  border-radius: 12px;
  padding: 16px;
  margin-bottom: 12px;
}}

.badge {{
  display: inline-block;
  padding: 2px 10px;
  border-radius: 999px;
  font-size: 12px;
  font-weight: 600;
}}

.badge-risk {{ background: var(--risk); color: #000; }}
.badge-todo {{ background: var(--todo); color: #000; }}
.badge-info {{ background: var(--info); color: #000; }}

.path {{
  font-family: ui-monospace, SFMono-Regular, Menlo, monospace;
  font-size: 13px;
  color: var(--muted);
  word-break: break-all;
}}

a {{
  color: var(--info);
  text-decoration: none;
}}
a:hover {{ text-decoration: underline; }}

.summary {{
  display: flex;
  gap: 12px;
  margin-bottom: 24px;
}}
.summary .card {{
  flex: 1;
  text-align: center;
}}

footer {{
  margin-top: 40px;
  color: var(--muted);
  font-size: 12px;
  text-align: center;
}}
</style>
</head>
<body>

<h1>🛠️ Zinkx Dev Assistant</h1>
<p class="path"><strong>Project:</strong> {project}</p>
<p class="path"><strong>Date:</strong> {date}</p>

<div class="summary">
  <div class="card">
    <div class="badge badge-risk">RISK</div>
    <h2>{risk_count}</h2>
  </div>
  <div class="card">
    <div class="badge badge-todo">TODO</div>
    <h2>{todo_count}</h2>
  </div>
  <div class="card">
    <div class="badge badge-info">INFO</div>
    <h2>{info_count}</h2>
  </div>
</div>

{sections}

<footer>
Generated by Zinkx Dev Assistant
</footer>

</body>
</html>
"""


def _section(title: str, kind: str, items: list[Finding]) -> str:
    if not items:
        return ""

    rows = []
    for f in items:
        if f.line:
            link = f"vscode://file/{f.path}:{f.line}"
            path = f'<a href="{link}">{f.path}:{f.line}</a>'
        else:
            path = f.path

        rows.append(f"""
        <div class="card">
          <span class="badge badge-{kind.lower()}">{kind}</span>
          <p>{f.detail}</p>
          <div class="path">{path}</div>
        </div>
        """)

    return f"<h2>{title}</h2>" + "\n".join(rows)


def write_html_report(findings: Iterable[Finding], project_root: str, out_dir: str) -> Path:
    outp = Path(out_dir).expanduser().resolve()
    outp.mkdir(parents=True, exist_ok=True)

    ts = datetime.now().strftime("%Y%m%d-%H%M%S")
    report_file = outp / f"report-{ts}.html"

    risks = [f for f in findings if f.kind == "RISK"]
    todos = [f for f in findings if f.kind == "TODO"]
    infos = [f for f in findings if f.kind == "INFO"]

    sections = (
        _section("🚨 Risks", "risk", risks) +
        _section("🧩 TODO / FIXME", "todo", todos) +
        _section("ℹ️ Info", "info", infos)
    )

    html = HTML_TEMPLATE.format(
        project=project_root,
        date=datetime.now().isoformat(timespec="seconds"),
        risk_count=len(risks),
        todo_count=len(todos),
        info_count=len(infos),
        sections=sections,
    )

    report_file.write_text(html, encoding="utf-8")
    return report_file
